### ISSUE TITLE
unable to setup overpass api successfully on test759 branch

### ISSUE THREAD

**Issue by rvpanchani** [mmd-osm/Overpass-API#7]
@mmd-osm - 
I was trying to build and deploy overpass api from your test759 branch to take benefit of all the improvements you made. 
I followed the instructions https://github.com/mmd-osm/Overpass-API/issues/3 and changed the make configuration https://github.com/mmd-osm/Overpass-API/issues/6#issuecomment-544642353 and built code successfully. 
I cloned zlib db from http://dev.overpass-api.de/clone/2020-10-20 and ran dispatcher it always fail with Unknown Index file 
then i tried with cloning lz4 db http://dev.overpass-api.de/clone/2020-08-12_lz4/ and running at least dispatcher directly first before starting updates. It also did not worked. 
then i tried initializing db with small data so i initialized db with luxembourg-latest.osm.bz2 and then running the conversion of gz to lz4 compression terminates by core dumped. 

Will it be possible to deploy test759 branch with the instructions i am referring and where ever default instructions are applicable.

**Comment by mmd-osm** [comment]
I’m afraid, this branch is not available for general use (see the respective notice on https://wiki.openstreetmap.org/wiki/User:Mmd/Overpass_API_-_experimental_corner), hence I can’t provide any guidance. You’ll have to wait until those features land in the official version.

**Comment by rvpanchani** [comment]
Thanks @mmd-osm for responding. Curiously awaiting for your changes in official version :)
